name: Build and Deploy to Azure Web App (uv)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          pipx install uv || pip install uv

      - name: Resolve & vendor deps with uv (in-project .venv)
        run: |
          uv sync --in-project --frozen

      - name: Archive app (includes .venv)
        run: |
          zip -r app.zip . -x ".git/*"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: .

      - name: Unzip
        run: unzip -o app.zip -d .

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .

      - name: Show deployed files
        run: ls -la
